# Build arguments
ARG SOURCE_CODE=.


# Use ubi8/go-toolset as base image
FROM registry.redhat.io/ubi8/go-toolset:1.21@sha256:742ae6ec1aef3e7faae488c47695fb64964d342aefecf52d23bd9d5e6731d0b6 as builder

## Build args to be used at this step
ARG SOURCE_CODE

USER root

# Needed musl-dev for github.com/mattn/go-sqlite3

COPY ${SOURCE_CODE}/go.mod ./
COPY ${SOURCE_CODE}/go.sum ./

# Copy the source
COPY ${SOURCE_CODE}/ ./

RUN GO111MODULE=on go build -o /bin/persistence_agent backend/src/agent/persistence/*.go

FROM registry.redhat.io/ubi8/ubi-minimal@sha256:c12e67af6a7e15113d76bc72f10bef2045c026c71ec8b7124c8a075458188a83
WORKDIR /bin

COPY --from=builder /bin/persistence_agent /bin/persistence_agent

ENV NAMESPACE ""

# Set Workflow TTL to 1 day. The way to use a different value for a particular Kubeflow Pipelines deployment is demonstrated in manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
ENV TTL_SECONDS_AFTER_WORKFLOW_FINISH 86400

# NUM_WORKERS indicates now many worker goroutines
ENV NUM_WORKERS 2

CMD persistence_agent --logtostderr=true --namespace=${NAMESPACE} --ttlSecondsAfterWorkflowFinish=${TTL_SECONDS_AFTER_WORKFLOW_FINISH} --numWorker ${NUM_WORKERS}

LABEL com.redhat.component="odh-ml-pipelines-persistenceagent-container" \
      name="managed-open-data-hub/odh-ml-pipelines-persistenceagent-container-rhel8" \
      git.url="${CI_DATA_SCIENCE_PIPELINES_TEKTON_UPSTREAM_URL}" \
      git.commit="${CI_DATA_SCIENCE_PIPELINES_TEKTON_UPSTREAM_COMMIT}" \
      summary="odh-ml-pipelines-persistenceagent" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-ml-pipelines-persistenceagent" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      description="odh-ml-pipelines-persistenceagent" \
      io.k8s.description="odh-ml-pipelines-persistenceagent" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
